import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { Todo } from "../todos/todoSlice";

export interface TodoModel
{
    _id?:string,
    title:string,
    completed:boolean
}

//https://jsonplaceholder.typicode.com/
export const todosApiSlice = createApi({
    baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:3000/api" }),
    reducerPath: "todosApi",
    // Tag types are used for caching and invalidation.
    tagTypes: ["Todos"],
   /* refetchOnFocus: true,*/
    refetchOnReconnect: true,
    endpoints: (build) => ({

        getAllTodos: build.query<TodoModel[],any>({
            query: () => `todos`,
            transformResponse: (response: TodoModel[], meta, arg) => {
                console.log('Response ',response);
                return response;
            },
            providesTags: (result, error, id) => [{ type: "Todos" }],
        }),
        saveTodo:build.mutation<TodoModel,TodoModel>({
            query: (todo:TodoModel) => ({
                url: `todos`,
                method: 'POST',
                body: todo,
            }),
            invalidatesTags: [{ type: 'Todos'}],
        }),
       /* deleteTodo:build.mutation<TodoModel,string>({
            query: (todoId:string) => ({
                url: `todos/${todoId}`,
                method: 'DELETE',

            }),
            invalidatesTags: [{ type: 'Todos'}],
        }),*/
        //Optimistic update
        deleteTodo:build.mutation<TodoModel,string>({
            query: (todoId:string) => ({
                url: `todos/${todoId}`,
                method: 'DELETE',

            }),
            
            //invalidatesTags: [{ type: 'Todos'}],
        }),
        updateTodo:build.mutation<TodoModel,TodoModel>({
            query: (todo:TodoModel) => ({
                url: `todos/${todo._id}`,
                method: 'PUT',
                body:todo,
            }),
            invalidatesTags: [{ type: 'Todos'}],
        }),
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
//console.log('TodosApiSlice ',todosApiSlice)
export const { useGetAllTodosQuery ,useSaveTodoMutation, useDeleteTodoMutation, useUpdateTodoMutation} = todosApiSlice;
